name: deploy to server

# Controls when the action will run. 
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-to-server-job:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deploy
        run: |
          curl "${{ secrets.AAPANELHOST }}/hook?access_key=${{ secrets.AAPANELKEY }}"